### ISSUE TITLE
LORAs not working with 2.5.45 (beta)

### ISSUE THREAD

**Issue by abtx** [easydiffusion/easydiffusion#1433]
**Describe the bug**
Whenever setting a lora the program will throw an error. I got one of the following:

**To Reproduce**
1. Make sure to use 2.5.45 (beta) with Loras enabled
2. Get one of the loras from somewhere, ex. [here](https://softwarekeep.com/help-center/best-stable-diffusion-models-to-try)
3. Try generating an image
 
`Error: Could not load the lora model! Reason: 'StableDiffusionPipeline' object has no attribute 'first'`
`Error: Could not load the lora model! Reason: 'StableDiffusionPipeline' object has no attribute 'cond'`

**Expected behavior**
An image should be generated

**Screenshots**
![Screenshot 2023-07-23 at 20 21 08](https://github.com/easydiffusion/easydiffusion/assets/5509711/bc874186-003f-477c-80e7-5922d9c1c001)

**Desktop (please complete the following information):**
 - OS: Ventura on Apple M2
 - Browser: Google Chrome 
 - Version: v114

**Comment by cmdr2** [comment]
Hi @abtx Please place those models in the `models/stable-diffusion` folder (as the article suggests). They are not LoRA models, those are stable diffusion models. Thanks!

**Comment by abtx** [comment]
> Hi @abtx Please place those models in the `models/stable-diffusion` folder (as the article suggests). The models in the article are not LoRA models, they are stable diffusion models. Thanks!

My bad! Thank you!

**Comment by FLA1tes** [comment]
hello everyone. I have the same error, I downloaded LoRA and copied along the way EasyDiffusion/models/lora. But it still gives me the same error. What I need to do?
![Снимок экрана (138)](https://github.com/easydiffusion/easydiffusion/assets/142105792/1821dba2-e01d-4622-a543-78057643c76e)

**Comment by LionGladiator** [comment]
> hello everyone. I have the same error, I downloaded LoRA and copied along the way EasyDiffusion/models/lora. But it still gives me the same error. What I need to do? ![Снимок экрана (138)](https://private-user-images.githubusercontent.com/142105792/260240397-1821dba2-e01d-4622-a543-78057643c76e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NjI5OTcsIm5iZiI6MTcxODQ2MjY5NywicGF0aCI6Ii8xNDIxMDU3OTIvMjYwMjQwMzk3LTE4MjFkYmEyLWUwMWQtNDYyMi1hNTQzLTc4MDU3NjQzYzc2ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNVQxNDQ0NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGY2OGFkYWU3NWZlNTgxYmFlMzE4NDAxNzczOWQ1YzEwYTBiZjY2MTRmNjU2ZjhlNDkzZTk2YzJlMTdkZTc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.G73f2mSul8YZCC2gAHu28_RESP0vFmdGoVT-L7nAv7I)

same as you sir how could i fix this T.T

**Comment by Menno5** [comment]
> hello everyone. I have the same error, I downloaded LoRA and copied along the way EasyDiffusion/models/lora. But it still gives me the same error. What I need to do? 

Most likely because you are trying to mix a SD1.5 model (hassakuhentaimodel_v13) with a SDXL Lora.
They either both have to be DS 1.5 or SDXL.
The same goes for ControlNet.
